friend.o: friend.cpp
		g++ -c friend.cpp -o friend.o 
Point3D.o: Point3D.cpp
		g++ -c Point3D.cpp -o Point3D.o 
Vector3D.o: Vector3D.cpp
		g++ -c Vector3D.cpp -o Vector3D.o 

friend: friend.o Point3D.o Vector3D.o
		g++ -o friend friend.o Point3D.o Vector3D.o 


